### PR TITLE
fix: remove unused dnd dependencies, dead code from ProjectView.js

### PR DESCRIPTION
**Pull request by shapirodaniel**
this PR removes react-dnd, react-dnd-html5-backend dependencies
removes commented out dnd-provider code in ProjectView

### CODE REVIEW

**Review by TwelveEyes — APPROVED** [review]

**Comment by shapirodaniel** [comment]
need to fix a few things due to new fonts, will include in this PR

**Comment by shapirodaniel** [comment]
ok, ready to go again! i added fixes to the single task view modal layout

**Comment by TwelveEyes** [comment]
looks good to me!

**Comment by shapirodaniel** [comment]
thanks gene!

**Review by johnnyvcoding — APPROVED** [review]

**Pull request merged**
